/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Exports a parsed standard directory JSON into a patient/study/series folder structure.
 *
 * Export types:
 * - 0: Copy original DICOM files
 * - 100: De-identify with tags only and export DICOM files
 * - 101: De-identify with tags + OCR and export DICOM files
 * Format-specific options (json_format_config):
 * For NIfTI (200): { "structure": "4d"/"3d" }
 * For Image (300): only JPEG output (no sub-format options)
 * For MP4 (400): { "fps": 24, "quality": "high"/"medium"/"low" }
 */
export declare function exportParsedStandardDirectory(jsonUtf8Content: string, exportRootDir: string, exportType: number, jsonDeidConfig?: string | undefined | null, jsonFormatConfig?: string | undefined | null): string

/**
 * Return the de-identification table as a JSON array:
 * [{"name": "Accession Number", "tag": "(0008,0050)", "action": "Z"}, ...]
 */
export declare function getDeidTable(): string
