/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Multimodal data export
 *
 * Reads multimodal data from the `labeling_details` table in cache.db,
 * and creates corresponding directory hierarchy based on the hierarchical structure
 * in the `data` field (project_folder|||PatientName|||StudyUID|||SeriesUID|||SOPUID),
 * then writes description.md, meta.json, and attachment files into the export directory.
 *
 * project_root_dir:  Project root directory (used to locate .pmtaro/cache.db)
 * export_root_dir:   Actual output directory path returned by the main export flow
 *                    (may already include a numeric suffix, e.g. "PatientName 1").
 *                    Based on this, only study/series subdirectories need to be added.
 * selection_json:    Selection JSON passed from the main export flow, used for UID→description name mapping.
 *
 * Returns a JSON string: { success, exportedCount, skippedCount, errors }
 */
export declare function exportMultimodalData(projectRootDir: string, exportRootDir: string, selectionJson: string): string

/**
 * Exports a parsed standard directory JSON into a patient/study/series folder structure.
 *
 * Export types:
 * - 0: Copy original DICOM files
 * - 100: De-identify with tags only and export DICOM files
 * - 101: De-identify with tags + OCR and export DICOM files
 * Format-specific options (json_format_config):
 * For NIfTI (200): { "structure": "4d"/"3d" }
 * For Image (300): only JPEG output (no sub-format options)
 * For MP4 (400): { "fps": 24, "quality": "high"/"medium"/"low" }
 */
export declare function exportParsedStandardDirectory(jsonUtf8Content: string, exportRootDir: string, exportType: number, jsonDeidConfig?: string | undefined | null, jsonFormatConfig?: string | undefined | null): string

/**
 * Return the de-identification table as a JSON array:
 * [{"name": "Accession Number", "tag": "(0008,0050)", "action": "Z"}, ...]
 */
export declare function getDeidTable(): string
