/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Exports a parsed standard directory JSON into a patient/study/series folder structure.
 *
 * Export types:
 * - 0: Copy original DICOM files
 * - 100: De-identify with tags only and export DICOM files
 * - 101: De-identify with tags + OCR and export DICOM files
 * - 200: Convert each series to NIfTI via dcmdjpeg + dcm2niix
 * - 300: Convert each instance to JPEG via dcm2img
 * - 400: Convert each series to MP4 via dcm2img (frames) + ffmpeg
 */
export declare function exportParsedStandardDirectory(jsonUtf8Content: string, exportRootDir: string, exportType: number): string
